import Head from "next/head"

const Home: React.FC = ({ children }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="font-nunito min-h-screen flex flex-col">
                {children}
            </main>
        </>
    )
}
export default Home
