export * from "./getMenu/getMenu"
export * from "./getPortfolios/getPortfolios"
export * from "./getSinglePortfolio/getSinglePortfolio"
export * from "./getAllCategories/getAllCategories"
export * from "./getCategoriesMenu/getCategoriesMenu"
export * from "./getSettings/getSettings"
export * from "./getSpecificPage/getSpecificPage"
